### ISSUE TITLE
Does the prefix-sum parallel really compute the prefix sum?

### ISSUE THREAD

**Issue by tonyskjellum** [vlnk/tools#1]
I am not getting the computation to produce all the prefixes; just the total.  Any visibility into this?

**Comment by Srinidhi1995** [comment]
Even I am not getting the computation to produce all the prefixes.

**Comment by vlnk** [comment]
Hello there, I am late with this issue :(

I don't know what is your goal here but this code is just homework for the university. I built it 6 years ago and it seems I won't reuse it. I even don't know if it is compatible with new gcc/clang releases.

So, feel free to copy and use this code for your own use. I will add a MIT license and a mention that I will never maintain this. I hope it helped you for some cases ;)
